package gpoker.players;

import gpoker.Move;
import gpoker.Player;
import org.jdom2.Element;

/**
 * CheckPlayer is a very simple players strategy and checks all the time (hence the name).
 * 
 * @author Edgar Ebensperger
 */
public class CheckPlayer extends Player {


	/**
	 * Creates the player via XML.
	 *
	 * @param element an XML player element
	 */
	public CheckPlayer(Element element) {

		super(element);
	}


	/**
	 * Constructs the player.
	 *
	 * @param name  the player's name
	 * @param chips the amount of chips the player has.
	 */
	public CheckPlayer(String name, int chips) {

		super(name, chips);
	}


	/**
	 * The CheckPlayers moves can not be trusted.
	 * 
	 * @return false.
	 */
	public boolean isTrusted() {
		return false;
	}
	
	
	/**
	 * Returns the move generated by the CheckPlayer. (which always is a check move)
	 * 
	 * @return	a CHECK move
	 */
	public Move act() {
		return new Move(Move.CHECK);
	}

}